"use client";

import {
  Bar,
  BarChart,
  CartesianGrid,
  XAxis,
  YAxis,
} from "recharts";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

import {
  ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "@/components/ui/chart";

import { DashboardAnalytics } from "@/types/admin.dashboard";

interface Props {
  data: DashboardAnalytics["categorySales"];
}

const chartConfig = {
  revenue: {
    label: "Revenue",
    color: "hsl(var(--chart-3))",
  },
} satisfies ChartConfig;

export default function CategorySalesChart({
  data,
}: Props) {
  return (
    <Card className="flex h-full flex-col justify-between overflow-hidden rounded-xl border border-slate-200/80 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-900">
      <CardHeader className="border-b border-slate-100 pb-4 dark:border-zinc-800/80">
        <div className="flex items-center gap-2">
          <span className="h-2 w-2 rounded-full bg-violet-500" />
          <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-zinc-500">
            Revenue Analytics
          </span>
        </div>
        <CardTitle className="text-lg font-bold tracking-tight text-slate-900 dark:text-zinc-50">
          Category Sales
        </CardTitle>
        <CardDescription className="text-xs text-slate-500 dark:text-zinc-400">
          Revenue generated by each category
        </CardDescription>
      </CardHeader>

      <CardContent className="p-6 pt-4">
        <ChartContainer
          config={chartConfig}
          className="h-350px w-full"
        >
          <BarChart
            accessibilityLayer
            data={data}
            layout="vertical"
            margin={{
              left: 10,
              right: 20,
              top: 10,
              bottom: 10,
            }}
          >
            <CartesianGrid
              horizontal={false}
              strokeDasharray="3 3"
              className="stroke-slate-100 dark:stroke-zinc-800"
            />

            <XAxis
              type="number"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={(value) =>
                `₹${Number(value).toLocaleString("en-IN")}`
              }
              className="text-xs font-mono text-slate-500 dark:text-zinc-400"
            />

            <YAxis
              dataKey="category"
              type="category"
              tickLine={false}
              axisLine={false}
              width={110}
              className="text-xs font-medium text-slate-700 dark:text-zinc-300"
            />

            <ChartTooltip
              cursor={{ fill: "rgba(0, 0, 0, 0.03)" }}
              content={
                <ChartTooltipContent
                  formatter={(value) => [
                    `₹${Number(value).toLocaleString("en-IN")}`,
                    "Revenue",
                  ]}
                />
              }
            />

            <Bar
              dataKey="revenue"
              fill="var(--color-revenue)"
              radius={[0, 6, 6, 0]}
              barSize={20}
            />
          </BarChart>
        </ChartContainer>
      </CardContent>
    </Card>
  );
}